import { Player } from '../supabase/types';

export const SERIE_A_SEASON = '2026/2027';

export const INITIAL_SERIE_A_PLAYERS: Omit<Player, 'created_at'>[] = [
  { id: "p-1", name: "Sommer Yann", team: "Inter", role: "P", initial_price: 18 },
  { id: "p-2", name: "Martinez Josep", team: "Inter", role: "P", initial_price: 5 },
  { id: "p-3", name: "Maignan Mike", team: "Milan", role: "P", initial_price: 17 },
  { id: "p-4", name: "Torriani Lorenzo", team: "Milan", role: "P", initial_price: 2 },
  { id: "p-5", name: "Di Gregorio Michele", team: "Juventus", role: "P", initial_price: 18 },
  { id: "p-6", name: "Perin Mattia", team: "Juventus", role: "P", initial_price: 3 },
  { id: "p-7", name: "Meret Alex", team: "Napoli", role: "P", initial_price: 16 },
  { id: "p-8", name: "Caprile Elia", team: "Napoli", role: "P", initial_price: 4 },
  { id: "p-9", name: "Carnesecchi Marco", team: "Atalanta", role: "P", initial_price: 15 },
  { id: "p-10", name: "Rui Patricio", team: "Atalanta", role: "P", initial_price: 2 },
  { id: "p-11", name: "Svilar Mile", team: "Roma", role: "P", initial_price: 14 },
  { id: "p-12", name: "Ryan Mathew", team: "Roma", role: "P", initial_price: 2 },
  { id: "p-13", name: "Provedel Ivan", team: "Lazio", role: "P", initial_price: 13 },
  { id: "p-14", name: "Mandas Christos", team: "Lazio", role: "P", initial_price: 3 },
  { id: "p-15", name: "De Gea David", team: "Fiorentina", role: "P", initial_price: 14 },
  { id: "p-16", name: "Terracciano Pietro", team: "Fiorentina", role: "P", initial_price: 3 },
  { id: "p-17", name: "Skorupski Lukasz", team: "Bologna", role: "P", initial_price: 12 },
  { id: "p-18", name: "Ravaglia Federico", team: "Bologna", role: "P", initial_price: 2 },
  { id: "p-19", name: "Milinkovic-Savic Vanja", team: "Torino", role: "P", initial_price: 12 },
  { id: "p-20", name: "Paleari Alberto", team: "Torino", role: "P", initial_price: 2 },
  { id: "p-21", name: "Audero Emil", team: "Como", role: "P", initial_price: 10 },
  { id: "p-22", name: "Reina Pepe", team: "Como", role: "P", initial_price: 1 },
  { id: "p-23", name: "Suzuki Zion", team: "Parma", role: "P", initial_price: 9 },
  { id: "p-24", name: "Chichizola Leandro", team: "Parma", role: "P", initial_price: 2 },
  { id: "p-25", name: "Okoye Maduka", team: "Udinese", role: "P", initial_price: 9 },
  { id: "p-26", name: "Gollini Pierluigi", team: "Genoa", role: "P", initial_price: 9 },
  { id: "p-27", name: "Leali Nicola", team: "Genoa", role: "P", initial_price: 2 },
  { id: "p-28", name: "Turati Stefano", team: "Monza", role: "P", initial_price: 8 },
  { id: "p-29", name: "Falcone Wladimiro", team: "Lecce", role: "P", initial_price: 9 },
  { id: "p-30", name: "Scuffet Simone", team: "Cagliari", role: "P", initial_price: 8 },
  { id: "p-31", name: "Montipò Lorenzo", team: "Verona", role: "P", initial_price: 8 },
  { id: "d-1", name: "Dimarco Federico", team: "Inter", role: "D", initial_price: 25 },
  { id: "d-2", name: "Bastoni Alessandro", team: "Inter", role: "D", initial_price: 17 },
  { id: "d-3", name: "Pavard Benjamin", team: "Inter", role: "D", initial_price: 14 },
  { id: "d-4", name: "Dumfries Denzel", team: "Inter", role: "D", initial_price: 16 },
  { id: "d-5", name: "Carlos Augusto", team: "Inter", role: "D", initial_price: 12 },
  { id: "d-6", name: "Bisseck Yann", team: "Inter", role: "D", initial_price: 12 },
  { id: "d-7", name: "Acerbi Francesco", team: "Inter", role: "D", initial_price: 9 },
  { id: "d-8", name: "Darmian Matteo", team: "Inter", role: "D", initial_price: 8 },
  { id: "d-9", name: "Hernandez Theo", team: "Milan", role: "D", initial_price: 23 },
  { id: "d-10", name: "Pavlovic Strahinja", team: "Milan", role: "D", initial_price: 13 },
  { id: "d-11", name: "Tomori Fikayo", team: "Milan", role: "D", initial_price: 12 },
  { id: "d-12", name: "Emerson Royal", team: "Milan", role: "D", initial_price: 10 },
  { id: "d-13", name: "Gabbia Matteo", team: "Milan", role: "D", initial_price: 9 },
  { id: "d-14", name: "Bremer Gleison", team: "Juventus", role: "D", initial_price: 20 },
  { id: "d-15", name: "Cambiaso Andrea", team: "Juventus", role: "D", initial_price: 16 },
  { id: "d-16", name: "Kalulu Pierre", team: "Juventus", role: "D", initial_price: 12 },
  { id: "d-17", name: "Gatti Federico", team: "Juventus", role: "D", initial_price: 11 },
  { id: "d-18", name: "Cabal Juan", team: "Juventus", role: "D", initial_price: 9 },
  { id: "d-19", name: "Danilo", team: "Juventus", role: "D", initial_price: 9 },
  { id: "d-20", name: "Buongiorno Alessandro", team: "Napoli", role: "D", initial_price: 16 },
  { id: "d-21", name: "Di Lorenzo Giovanni", team: "Napoli", role: "D", initial_price: 15 },
  { id: "d-22", name: "Rrahmani Amir", team: "Napoli", role: "D", initial_price: 12 },
  { id: "d-23", name: "Spinazzola Leonardo", team: "Napoli", role: "D", initial_price: 10 },
  { id: "d-24", name: "Olivera Mathias", team: "Napoli", role: "D", initial_price: 9 },
  { id: "d-25", name: "Mazzocchi Pasquale", team: "Napoli", role: "D", initial_price: 6 },
  { id: "d-26", name: "Bellanova Raoul", team: "Atalanta", role: "D", initial_price: 15 },
  { id: "d-27", name: "Zappacosta Davide", team: "Atalanta", role: "D", initial_price: 13 },
  { id: "d-28", name: "Ruggeri Matteo", team: "Atalanta", role: "D", initial_price: 11 },
  { id: "d-29", name: "Hien Isak", team: "Atalanta", role: "D", initial_price: 10 },
  { id: "d-30", name: "Kolasinac Sead", team: "Atalanta", role: "D", initial_price: 9 },
  { id: "d-31", name: "Kossounou Odilon", team: "Atalanta", role: "D", initial_price: 9 },
  { id: "d-32", name: "Scalvini Giorgio", team: "Atalanta", role: "D", initial_price: 10 },
  { id: "d-33", name: "Mancini Gianluca", team: "Roma", role: "D", initial_price: 12 },
  { id: "d-34", name: "Angelino Jose", team: "Roma", role: "D", initial_price: 12 },
  { id: "d-35", name: "Ndicka Evan", team: "Roma", role: "D", initial_price: 10 },
  { id: "d-36", name: "Hermoso Mario", team: "Roma", role: "D", initial_price: 10 },
  { id: "d-37", name: "Hummels Mats", team: "Roma", role: "D", initial_price: 9 },
  { id: "d-38", name: "Saelemaekers Alexis", team: "Roma", role: "D", initial_price: 11 },
  { id: "d-39", name: "Tavares Nuno", team: "Lazio", role: "D", initial_price: 15 },
  { id: "d-40", name: "Romagnoli Alessio", team: "Lazio", role: "D", initial_price: 11 },
  { id: "d-41", name: "Gila Mario", team: "Lazio", role: "D", initial_price: 10 },
  { id: "d-42", name: "Lazzari Manuel", team: "Lazio", role: "D", initial_price: 9 },
  { id: "d-43", name: "Marusic Adam", team: "Lazio", role: "D", initial_price: 7 },
  { id: "d-44", name: "Gosens Robin", team: "Fiorentina", role: "D", initial_price: 16 },
  { id: "d-45", name: "Dodo", team: "Fiorentina", role: "D", initial_price: 11 },
  { id: "d-46", name: "Ranieri Luca", team: "Fiorentina", role: "D", initial_price: 9 },
  { id: "d-47", name: "Pongracic Marin", team: "Fiorentina", role: "D", initial_price: 9 },
  { id: "d-48", name: "Biraghi Cristiano", team: "Fiorentina", role: "D", initial_price: 8 },
  { id: "d-49", name: "Posch Stefan", team: "Bologna", role: "D", initial_price: 12 },
  { id: "d-50", name: "Beukema Sam", team: "Bologna", role: "D", initial_price: 11 },
  { id: "d-51", name: "Miranda Juan", team: "Bologna", role: "D", initial_price: 9 },
  { id: "d-52", name: "Lucumi Jhon", team: "Bologna", role: "D", initial_price: 8 },
  { id: "d-53", name: "Coco Saul", team: "Torino", role: "D", initial_price: 12 },
  { id: "d-54", name: "Vojvoda Mergim", team: "Torino", role: "D", initial_price: 9 },
  { id: "d-55", name: "Masina Adam", team: "Torino", role: "D", initial_price: 7 },
  { id: "d-56", name: "Dossena Alberto", team: "Como", role: "D", initial_price: 9 },
  { id: "d-57", name: "Alberto Moreno", team: "Como", role: "D", initial_price: 9 },
  { id: "d-58", name: "Kempf Oliver", team: "Como", role: "D", initial_price: 8 },
  { id: "d-59", name: "Valeri Emanuele", team: "Parma", role: "D", initial_price: 9 },
  { id: "d-60", name: "Delprato Enrico", team: "Parma", role: "D", initial_price: 8 },
  { id: "d-61", name: "Circati Alessandro", team: "Parma", role: "D", initial_price: 7 },
  { id: "d-62", name: "Bijol Jaka", team: "Udinese", role: "D", initial_price: 10 },
  { id: "d-63", name: "Ehizibue Kingsley", team: "Udinese", role: "D", initial_price: 8 },
  { id: "d-64", name: "Martin Aaron", team: "Genoa", role: "D", initial_price: 9 },
  { id: "d-65", name: "Vasquez Johan", team: "Genoa", role: "D", initial_price: 8 },
  { id: "d-66", name: "Viti Mattia", team: "Empoli", role: "D", initial_price: 8 },
  { id: "d-67", name: "Dorgu Patrick", team: "Lecce", role: "D", initial_price: 11 },
  { id: "d-68", name: "Gaspar Kialonda", team: "Lecce", role: "D", initial_price: 8 },
  { id: "d-69", name: "Luperto Sebastiano", team: "Cagliari", role: "D", initial_price: 8 },
  { id: "d-70", name: "Zappa Gabriele", team: "Cagliari", role: "D", initial_price: 7 },
  { id: "d-71", name: "Birindelli Samuele", team: "Monza", role: "D", initial_price: 6 },
  { id: "d-72", name: "Celik Zeki", team: "Roma", role: "D", initial_price: 7 },
  { id: "d-73", name: "Comuzzo Pietro", team: "Fiorentina", role: "D", initial_price: 8 },
  { id: "d-74", name: "De Winter Koni", team: "Genoa", role: "D", initial_price: 8 },
  { id: "d-75", name: "Ghilardi Daniele", team: "Verona", role: "D", initial_price: 5 },
  { id: "d-76", name: "Haps Ridgeciano", team: "Venezia", role: "D", initial_price: 6 },
  { id: "d-77", name: "Idzes Jay", team: "Venezia", role: "D", initial_price: 8 },
  { id: "d-78", name: "Jimenez Alex", team: "Milan", role: "D", initial_price: 6 },
  { id: "d-79", name: "Kabasele Christian", team: "Udinese", role: "D", initial_price: 6 },
  { id: "d-80", name: "Kamara Hassane", team: "Udinese", role: "D", initial_price: 7 },
  { id: "d-81", name: "Marcandalli Alessandro", team: "Genoa", role: "D", initial_price: 5 },
  { id: "d-82", name: "Molina Salvatore", team: "Monza", role: "D", initial_price: 5 },
  { id: "d-83", name: "Monterisi Ilario", team: "Frosinone", role: "D", initial_price: 5 },
  { id: "d-84", name: "Obert Adam", team: "Cagliari", role: "D", initial_price: 5 },
  { id: "d-85", name: "Solet Oumar", team: "Udinese", role: "D", initial_price: 8 },
  { id: "d-86", name: "Tiago Gabriel", team: "Cagliari", role: "D", initial_price: 5 },
  { id: "d-87", name: "Van Der Brempt Ignace", team: "Como", role: "D", initial_price: 6 },
  { id: "d-88", name: "Zortea Nadir", team: "Cagliari", role: "D", initial_price: 10 },
  { id: "d-89", name: "Bartesaghi Davide", team: "Milan", role: "D", initial_price: 4 },
  { id: "d-90", name: "Mina Yerry", team: "Cagliari", role: "D", initial_price: 8 },
  { id: "d-91", name: "Kristensen Thomas", team: "Udinese", role: "D", initial_price: 7 },
  { id: "d-92", name: "Abankwah James", team: "Udinese", role: "D", initial_price: 4 },
  { id: "c-1", name: "Calhanoglu Hakan", team: "Inter", role: "C", initial_price: 26 },
  { id: "c-2", name: "Barella Nicolo", team: "Inter", role: "C", initial_price: 23 },
  { id: "c-3", name: "Frattesi Davide", team: "Inter", role: "C", initial_price: 18 },
  { id: "c-4", name: "Zielinski Piotr", team: "Inter", role: "C", initial_price: 13 },
  { id: "c-5", name: "Mkhitaryan Henrikh", team: "Inter", role: "C", initial_price: 13 },
  { id: "c-6", name: "Asllani Kristjan", team: "Inter", role: "C", initial_price: 8 },
  { id: "c-7", name: "Pulisic Christian", team: "Milan", role: "C", initial_price: 28 },
  { id: "c-8", name: "Reijnders Tijjani", team: "Milan", role: "C", initial_price: 17 },
  { id: "c-9", name: "Fofana Youssouf", team: "Milan", role: "C", initial_price: 13 },
  { id: "c-10", name: "Loftus-Cheek Ruben", team: "Milan", role: "C", initial_price: 14 },
  { id: "c-11", name: "Chukwueze Samuel", team: "Milan", role: "C", initial_price: 13 },
  { id: "c-12", name: "Musah Yunus", team: "Milan", role: "C", initial_price: 9 },
  { id: "c-13", name: "Koopmeiners Teun", team: "Juventus", role: "C", initial_price: 27 },
  { id: "c-14", name: "Conceicao Francisco", team: "Juventus", role: "C", initial_price: 17 },
  { id: "c-15", name: "Thuram Khephren", team: "Juventus", role: "C", initial_price: 14 },
  { id: "c-16", name: "Douglas Luiz", team: "Juventus", role: "C", initial_price: 15 },
  { id: "c-17", name: "Locatelli Manuel", team: "Juventus", role: "C", initial_price: 11 },
  { id: "c-18", name: "McKennie Weston", team: "Juventus", role: "C", initial_price: 11 },
  { id: "c-19", name: "McTominay Scott", team: "Napoli", role: "C", initial_price: 23 },
  { id: "c-20", name: "Neres David", team: "Napoli", role: "C", initial_price: 19 },
  { id: "c-21", name: "Politano Matteo", team: "Napoli", role: "C", initial_price: 17 },
  { id: "c-22", name: "Anguissa Frank", team: "Napoli", role: "C", initial_price: 14 },
  { id: "c-23", name: "Lobotka Stanislav", team: "Napoli", role: "C", initial_price: 12 },
  { id: "c-24", name: "Gilmour Billy", team: "Napoli", role: "C", initial_price: 10 },
  { id: "c-25", name: "De Ketelaere Charles", team: "Atalanta", role: "C", initial_price: 24 },
  { id: "c-26", name: "Pasalic Mario", team: "Atalanta", role: "C", initial_price: 17 },
  { id: "c-27", name: "Samardzic Lazar", team: "Atalanta", role: "C", initial_price: 17 },
  { id: "c-28", name: "Ederson Jose", team: "Atalanta", role: "C", initial_price: 15 },
  { id: "c-29", name: "Brescianini Marco", team: "Atalanta", role: "C", initial_price: 13 },
  { id: "c-30", name: "Zaniolo Nicolo", team: "Atalanta", role: "C", initial_price: 13 },
  { id: "c-31", name: "Pellegrini Lorenzo", team: "Roma", role: "C", initial_price: 17 },
  { id: "c-32", name: "Kone Manu", team: "Roma", role: "C", initial_price: 13 },
  { id: "c-33", name: "Cristante Bryan", team: "Roma", role: "C", initial_price: 10 },
  { id: "c-34", name: "Baldanzi Tommaso", team: "Roma", role: "C", initial_price: 11 },
  { id: "c-35", name: "Le Fee Enzo", team: "Roma", role: "C", initial_price: 10 },
  { id: "c-36", name: "Zaccagni Mattia", team: "Lazio", role: "C", initial_price: 23 },
  { id: "c-37", name: "Guendouzi Matteo", team: "Lazio", role: "C", initial_price: 13 },
  { id: "c-38", name: "Rovella Nicolo", team: "Lazio", role: "C", initial_price: 11 },
  { id: "c-39", name: "Isaksen Gustav", team: "Lazio", role: "C", initial_price: 12 },
  { id: "c-40", name: "Dele-Bashiru Fisayo", team: "Lazio", role: "C", initial_price: 10 },
  { id: "c-41", name: "Gudmundsson Albert", team: "Fiorentina", role: "C", initial_price: 25 },
  { id: "c-42", name: "Colpani Andrea", team: "Fiorentina", role: "C", initial_price: 17 },
  { id: "c-43", name: "Bove Edoardo", team: "Fiorentina", role: "C", initial_price: 12 },
  { id: "c-44", name: "Adli Yacine", team: "Fiorentina", role: "C", initial_price: 11 },
  { id: "c-45", name: "Cataldi Danilo", team: "Fiorentina", role: "C", initial_price: 9 },
  { id: "c-46", name: "Orsolini Riccardo", team: "Bologna", role: "C", initial_price: 24 },
  { id: "c-47", name: "Ferguson Lewis", team: "Bologna", role: "C", initial_price: 17 },
  { id: "c-48", name: "Fabbian Giovanni", team: "Bologna", role: "C", initial_price: 14 },
  { id: "c-49", name: "Ndoye Dan", team: "Bologna", role: "C", initial_price: 14 },
  { id: "c-50", name: "Freuler Remo", team: "Bologna", role: "C", initial_price: 10 },
  { id: "c-51", name: "Ricci Samuele", team: "Torino", role: "C", initial_price: 12 },
  { id: "c-52", name: "Vlasic Nikola", team: "Torino", role: "C", initial_price: 15 },
  { id: "c-53", name: "Ilic Ivan", team: "Torino", role: "C", initial_price: 12 },
  { id: "c-54", name: "Lazaro Valentino", team: "Torino", role: "C", initial_price: 10 },
  { id: "c-55", name: "Paz Nico", team: "Como", role: "C", initial_price: 20 },
  { id: "c-56", name: "Strefezza Gabriel", team: "Como", role: "C", initial_price: 15 },
  { id: "c-57", name: "Fadera Alieu", team: "Como", role: "C", initial_price: 12 },
  { id: "c-58", name: "Perrone Maximo", team: "Como", role: "C", initial_price: 11 },
  { id: "c-59", name: "Man Dennis", team: "Parma", role: "C", initial_price: 19 },
  { id: "c-60", name: "Bernabé Adrian", team: "Parma", role: "C", initial_price: 14 },
  { id: "c-61", name: "Sohm Simon", team: "Parma", role: "C", initial_price: 10 },
  { id: "c-62", name: "Pessina Matteo", team: "Monza", role: "C", initial_price: 12 },
  { id: "c-63", name: "Kyriakopoulos Giorgos", team: "Monza", role: "C", initial_price: 9 },
  { id: "c-64", name: "Lovric Sandi", team: "Udinese", role: "C", initial_price: 11 },
  { id: "c-65", name: "Ekkelenkamp Jurgen", team: "Udinese", role: "C", initial_price: 10 },
  { id: "c-66", name: "Frendrup Morten", team: "Genoa", role: "C", initial_price: 11 },
  { id: "c-67", name: "Malinovskyi Ruslan", team: "Genoa", role: "C", initial_price: 10 },
  { id: "c-68", name: "Gaetano Gianluca", team: "Cagliari", role: "C", initial_price: 12 },
  { id: "c-69", name: "Marin Razvan", team: "Cagliari", role: "C", initial_price: 10 },
  { id: "c-70", name: "Suslov Tomas", team: "Verona", role: "C", initial_price: 12 },
  { id: "c-71", name: "Adopo Michel", team: "Cagliari", role: "C", initial_price: 6 },
  { id: "c-72", name: "Adzic Vasilije", team: "Juventus", role: "C", initial_price: 7 },
  { id: "c-73", name: "Atta Arthur", team: "Udinese", role: "C", initial_price: 6 },
  { id: "c-74", name: "Berisha Medon", team: "Lecce", role: "C", initial_price: 6 },
  { id: "c-75", name: "Cambiaghi Nicolo", team: "Bologna", role: "C", initial_price: 11 },
  { id: "c-76", name: "Da Cunha Lucas", team: "Como", role: "C", initial_price: 10 },
  { id: "c-77", name: "De Roon Marten", team: "Atalanta", role: "C", initial_price: 10 },
  { id: "c-78", name: "Fazzini Jacopo", team: "Empoli", role: "C", initial_price: 11 },
  { id: "c-79", name: "Folorunsho Michael", team: "Fiorentina", role: "C", initial_price: 11 },
  { id: "c-80", name: "Karlstrom Jesper", team: "Udinese", role: "C", initial_price: 7 },
  { id: "c-81", name: "Liberali Mattia", team: "Milan", role: "C", initial_price: 4 },
  { id: "c-82", name: "Maleh Youssef", team: "Empoli", role: "C", initial_price: 7 },
  { id: "c-83", name: "Mandragora Rolando", team: "Fiorentina", role: "C", initial_price: 9 },
  { id: "c-84", name: "Nicolussi Caviglia Hans", team: "Venezia", role: "C", initial_price: 9 },
  { id: "c-85", name: "Njie Alieu", team: "Torino", role: "C", initial_price: 5 },
  { id: "c-86", name: "Odgaard Jens", team: "Bologna", role: "C", initial_price: 11 },
  { id: "c-87", name: "Piotrowski Jakub", team: "Udinese", role: "C", initial_price: 6 },
  { id: "c-88", name: "Pisilli Niccolo", team: "Roma", role: "C", initial_price: 8 },
  { id: "c-89", name: "Stankovic Filip", team: "Venezia", role: "C", initial_price: 6 },
  { id: "c-90", name: "Thorstvedt Kristian", team: "Sassuolo", role: "C", initial_price: 9 },
  { id: "c-91", name: "Volpato Cristian", team: "Sassuolo", role: "C", initial_price: 7 },
  { id: "c-92", name: "Zalewski Nicola", team: "Roma", role: "C", initial_price: 8 },
  { id: "c-93", name: "Casadei Cesare", team: "Monza", role: "C", initial_price: 7 },
  { id: "c-94", name: "Gonzalez Nicolas", team: "Juventus", role: "C", initial_price: 18 },
  { id: "a-1", name: "Martinez Lautaro", team: "Inter", role: "A", initial_price: 39 },
  { id: "a-2", name: "Thuram Marcus", team: "Inter", role: "A", initial_price: 33 },
  { id: "a-3", name: "Taremi Mehdi", team: "Inter", role: "A", initial_price: 18 },
  { id: "a-4", name: "Arnautovic Marko", team: "Inter", role: "A", initial_price: 7 },
  { id: "a-5", name: "Vlahovic Dusan", team: "Juventus", role: "A", initial_price: 36 },
  { id: "a-6", name: "Yildiz Kenan", team: "Juventus", role: "A", initial_price: 24 },
  { id: "a-7", name: "Milik Arkadiusz", team: "Juventus", role: "A", initial_price: 9 },
  { id: "a-8", name: "Leao Rafael", team: "Milan", role: "A", initial_price: 32 },
  { id: "a-9", name: "Morata Alvaro", team: "Milan", role: "A", initial_price: 28 },
  { id: "a-10", name: "Abraham Tammy", team: "Milan", role: "A", initial_price: 17 },
  { id: "a-11", name: "Okafor Noah", team: "Milan", role: "A", initial_price: 11 },
  { id: "a-12", name: "Lukaku Romelu", team: "Napoli", role: "A", initial_price: 35 },
  { id: "a-13", name: "Kvaratskhelia Khvicha", team: "Napoli", role: "A", initial_price: 34 },
  { id: "a-14", name: "Simeone Giovanni", team: "Napoli", role: "A", initial_price: 10 },
  { id: "a-15", name: "Raspadori Giacomo", team: "Napoli", role: "A", initial_price: 12 },
  { id: "a-16", name: "Lookman Ademola", team: "Atalanta", role: "A", initial_price: 33 },
  { id: "a-17", name: "Retegui Mateo", team: "Atalanta", role: "A", initial_price: 32 },
  { id: "a-18", name: "Scamacca Gianluca", team: "Atalanta", role: "A", initial_price: 17 },
  { id: "a-19", name: "Dovbyk Artem", team: "Roma", role: "A", initial_price: 31 },
  { id: "a-20", name: "Dybala Paulo", team: "Roma", role: "A", initial_price: 28 },
  { id: "a-21", name: "Soulé Matias", team: "Roma", role: "A", initial_price: 21 },
  { id: "a-22", name: "Shomurodov Eldor", team: "Roma", role: "A", initial_price: 8 },
  { id: "a-23", name: "Castellanos Valentin", team: "Lazio", role: "A", initial_price: 26 },
  { id: "a-24", name: "Dia Boulaye", team: "Lazio", role: "A", initial_price: 23 },
  { id: "a-25", name: "Noslin Tijjani", team: "Lazio", role: "A", initial_price: 15 },
  { id: "a-26", name: "Pedro", team: "Lazio", role: "A", initial_price: 9 },
  { id: "a-27", name: "Kean Moise", team: "Fiorentina", role: "A", initial_price: 27 },
  { id: "a-28", name: "Beltran Lucas", team: "Fiorentina", role: "A", initial_price: 13 },
  { id: "a-29", name: "Kouame Christian", team: "Fiorentina", role: "A", initial_price: 9 },
  { id: "a-30", name: "Castro Santiago", team: "Bologna", role: "A", initial_price: 22 },
  { id: "a-31", name: "Dallinga Thijs", team: "Bologna", role: "A", initial_price: 17 },
  { id: "a-32", name: "Zapata Duvan", team: "Torino", role: "A", initial_price: 23 },
  { id: "a-33", name: "Adams Che", team: "Torino", role: "A", initial_price: 18 },
  { id: "a-34", name: "Sanabria Antonio", team: "Torino", role: "A", initial_price: 12 },
  { id: "a-35", name: "Lucca Lorenzo", team: "Udinese", role: "A", initial_price: 20 },
  { id: "a-36", name: "Thauvin Florian", team: "Udinese", role: "A", initial_price: 18 },
  { id: "a-37", name: "Brenner", team: "Udinese", role: "A", initial_price: 10 },
  { id: "a-38", name: "Pinamonti Andrea", team: "Genoa", role: "A", initial_price: 19 },
  { id: "a-39", name: "Vitinha", team: "Genoa", role: "A", initial_price: 13 },
  { id: "a-40", name: "Bonny Ange-Yoan", team: "Parma", role: "A", initial_price: 18 },
  { id: "a-41", name: "Mihaila Valentin", team: "Parma", role: "A", initial_price: 12 },
  { id: "a-42", name: "Cancellieri Matteo", team: "Parma", role: "A", initial_price: 12 },
  { id: "a-43", name: "Cutrone Patrick", team: "Como", role: "A", initial_price: 18 },
  { id: "a-44", name: "Belotti Andrea", team: "Como", role: "A", initial_price: 12 },
  { id: "a-45", name: "Krstovic Nikola", team: "Lecce", role: "A", initial_price: 17 },
  { id: "a-46", name: "Rebic Ante", team: "Lecce", role: "A", initial_price: 10 },
  { id: "a-47", name: "Djuric Milan", team: "Monza", role: "A", initial_price: 13 },
  { id: "a-48", name: "Daniel Maldini", team: "Monza", role: "A", initial_price: 14 },
  { id: "a-49", name: "Caprari Gianluca", team: "Monza", role: "A", initial_price: 10 },
  { id: "a-50", name: "Piccoli Roberto", team: "Cagliari", role: "A", initial_price: 15 },
  { id: "a-51", name: "Luvumbo Zito", team: "Cagliari", role: "A", initial_price: 13 },
  { id: "a-52", name: "Tengstedt Casper", team: "Verona", role: "A", initial_price: 14 },
  { id: "a-53", name: "Mosquera Daniel", team: "Verona", role: "A", initial_price: 12 },
  { id: "a-54", name: "Colombo Lorenzo", team: "Empoli", role: "A", initial_price: 13 },
  { id: "a-55", name: "Esposito Sebastiano", team: "Empoli", role: "A", initial_price: 13 },
  { id: "a-56", name: "Berardi Domenico", team: "Sassuolo", role: "A", initial_price: 24 },
  { id: "a-57", name: "Camarda Francesco", team: "Milan", role: "A", initial_price: 5 },
  { id: "a-58", name: "Mota Dany", team: "Monza", role: "A", initial_price: 12 },
  { id: "a-59", name: "Davis Keinan", team: "Udinese", role: "A", initial_price: 9 },
  { id: "a-60", name: "Lauriente Armand", team: "Sassuolo", role: "A", initial_price: 14 },
  { id: "a-61", name: "Ngonge Cyril", team: "Napoli", role: "A", initial_price: 11 },
  { id: "a-62", name: "Noslin Tijjani", team: "Lazio", role: "A", initial_price: 14 },
  { id: "a-63", name: "Pellegrino Marco", team: "Milan", role: "A", initial_price: 5 },
  { id: "a-64", name: "Esposito Francesco Pio", team: "Spezia", role: "A", initial_price: 7 },
  { id: "a-65", name: "Raimondo Antonio", team: "Venezia", role: "A", initial_price: 8 },
  { id: "a-66", name: "Toure El Bilal", team: "Atalanta", role: "A", initial_price: 10 },
  { id: "q-5841", name: "Svilar", team: "Roma", role: "P", initial_price: 19 },
  { id: "q-4431", name: "Carnesecchi", team: "Atalanta", role: "P", initial_price: 16 },
  { id: "q-5116", name: "Martinez Jo.", team: "Inter", role: "P", initial_price: 16 },
  { id: "q-4964", name: "Vicario", team: "Juventus", role: "P", initial_price: 16 },
  { id: "q-6966", name: "Butez", team: "Como", role: "P", initial_price: 15 },
  { id: "q-4312", name: "Maignan", team: "Milan", role: "P", initial_price: 14 },
  { id: "q-4360", name: "Caprile", team: "Cagliari", role: "P", initial_price: 11 },
  { id: "q-6482", name: "Mandas", team: "Lazio", role: "P", initial_price: 11 },
  { id: "q-133", name: "Skorupski", team: "Bologna", role: "P", initial_price: 10 },
  { id: "q-2521", name: "De Gea", team: "Fiorentina", role: "P", initial_price: 10 },
  { id: "q-572", name: "Meret", team: "Napoli", role: "P", initial_price: 10 },
  { id: "q-6534", name: "Perri", team: "Torino", role: "P", initial_price: 9 },
  { id: "q-2134", name: "Falcone", team: "Lecce", role: "P", initial_price: 8 },
  { id: "q-6462", name: "Okoye", team: "Udinese", role: "P", initial_price: 8 },
  { id: "q-6344", name: "Sanchez Ro.", team: "Como", role: "P", initial_price: 8 },
  { id: "q-7332", name: "Bijlow", team: "Genoa", role: "P", initial_price: 7 },
  { id: "q-6415", name: "Palmisani", team: "Frosinone", role: "P", initial_price: 6 },
  { id: "q-7411", name: "Daffara", team: "Parma", role: "P", initial_price: 6 },
  { id: "q-4236", name: "Muric", team: "Sassuolo", role: "P", initial_price: 6 },
  { id: "q-2170", name: "Milinkovic-Savic V.", team: "Napoli", role: "P", initial_price: 5 },
  { id: "q-6248", name: "Stankovic F.", team: "Venezia", role: "P", initial_price: 5 },
  { id: "q-4485", name: "Thiam", team: "Monza", role: "P", initial_price: 4 },
  { id: "q-6662", name: "Corvi", team: "Parma", role: "P", initial_price: 3 },
  { id: "q-7172", name: "Pessina Mas.", team: "Bologna", role: "P", initial_price: 2 },
  { id: "q-4", name: "Sportiello", team: "Atalanta", role: "P", initial_price: 1 },
  { id: "q-7533", name: "Happonen", team: "Bologna", role: "P", initial_price: 1 },
  { id: "q-6650", name: "Sherri", team: "Cagliari", role: "P", initial_price: 1 },
  { id: "q-7301", name: "Tornqvist", team: "Monza", role: "P", initial_price: 1 },
  { id: "q-2809", name: "Vigorito", team: "Como", role: "P", initial_price: 1 },
  { id: "q-6403", name: "Christensen O.", team: "Fiorentina", role: "P", initial_price: 1 },
  { id: "q-158", name: "Lezzerini", team: "Fiorentina", role: "P", initial_price: 1 },
  { id: "q-7463", name: "Desplanches", team: "Frosinone", role: "P", initial_price: 1 },
  { id: "q-7466", name: "Lolic", team: "Frosinone", role: "P", initial_price: 1 },
  { id: "q-219", name: "Sommariva", team: "Genoa", role: "P", initial_price: 1 },
  { id: "q-6569", name: "Stolz", team: "Genoa", role: "P", initial_price: 1 },
  { id: "q-1926", name: "Di Gennaro", team: "Inter", role: "P", initial_price: 1 },
  { id: "q-2814", name: "Provedel", team: "Inter", role: "P", initial_price: 1 },
  { id: "q-1930", name: "Pinsoglio", team: "Juventus", role: "P", initial_price: 1 },
  { id: "q-7337", name: "Motta", team: "Lazio", role: "P", initial_price: 1 },
  { id: "q-7534", name: "Renzetti", team: "Lazio", role: "P", initial_price: 1 },
  { id: "q-2815", name: "Terracciano", team: "Milan", role: "P", initial_price: 1 },
  { id: "q-6813", name: "Torriani", team: "Milan", role: "P", initial_price: 1 },
  { id: "q-7475", name: "Strajnar", team: "Monza", role: "P", initial_price: 1 },
  { id: "q-2845", name: "Contini", team: "Napoli", role: "P", initial_price: 1 },
  { id: "q-7048", name: "De Marzi", team: "Roma", role: "P", initial_price: 1 },
  { id: "q-610", name: "Gollini", team: "Roma", role: "P", initial_price: 1 },
  { id: "q-4518", name: "Russo A.", team: "Sassuolo", role: "P", initial_price: 1 },
  { id: "q-4867", name: "Turati", team: "Sassuolo", role: "P", initial_price: 1 },
  { id: "q-7457", name: "Mascardi", team: "Torino", role: "P", initial_price: 1 },
  { id: "q-7363", name: "Siviero", team: "Torino", role: "P", initial_price: 1 },
  { id: "q-543", name: "Padelli", team: "Udinese", role: "P", initial_price: 1 },
  { id: "q-6671", name: "Grandi", team: "Venezia", role: "P", initial_price: 1 },
  { id: "q-7531", name: "Pozzi", team: "Venezia", role: "P", initial_price: 1 },
  { id: "q-2127", name: "Satalino", team: "Sassuolo", role: "P", initial_price: 1 },
  { id: "q-7557", name: "Penev", team: "Lecce", role: "P", initial_price: 1 },
  { id: "q-7560", name: "Pisseri", team: "Frosinone", role: "P", initial_price: 1 },
  { id: "q-3", name: "Radunovic", team: "Cagliari", role: "P", initial_price: 1 },
  { id: "q-4957", name: "Montipò", team: "Venezia", role: "P", initial_price: 1 },
  { id: "q-4468", name: "Bleve", team: "Lecce", role: "P", initial_price: 1 },
  { id: "q-7603", name: "Grabara", team: "Juventus", role: "P", initial_price: 1 },
  { id: "q-7611", name: "Mrozek", team: "Udinese", role: "P", initial_price: 1 },
  { id: "q-2874", name: "Ghidotti", team: "Parma", role: "P", initial_price: 1 },
  { id: "q-7626", name: "Pompei", team: "Atalanta", role: "P", initial_price: 1 },
  { id: "q-254", name: "Dimarco", team: "Inter", role: "D", initial_price: 30 },
  { id: "q-7181", name: "Wesley", team: "Roma", role: "D", initial_price: 18 },
  { id: "q-4998", name: "Molina N.", team: "Roma", role: "D", initial_price: 18 },
  { id: "q-2788", name: "Bremer", team: "Juventus", role: "D", initial_price: 16 },
  { id: "q-4159", name: "Akanji", team: "Inter", role: "D", initial_price: 15 },
  { id: "q-2296", name: "Mancini", team: "Roma", role: "D", initial_price: 15 },
  { id: "q-2120", name: "Bastoni", team: "Inter", role: "D", initial_price: 14 },
  { id: "q-4409", name: "Rrahmani", team: "Napoli", role: "D", initial_price: 14 },
  { id: "q-4976", name: "Kalulu", team: "Juventus", role: "D", initial_price: 13 },
  { id: "q-5022", name: "Pavlovic", team: "Milan", role: "D", initial_price: 13 },
  { id: "q-6956", name: "Solet", team: "Udinese", role: "D", initial_price: 13 },
  { id: "q-6869", name: "Ramon", team: "Como", role: "D", initial_price: 12 },
  { id: "q-6217", name: "Bisseck", team: "Inter", role: "D", initial_price: 12 },
  { id: "q-2514", name: "Stones", team: "Inter", role: "D", initial_price: 12 },
  { id: "q-5833", name: "Gila", team: "Milan", role: "D", initial_price: 12 },
  { id: "q-2816", name: "Di Lorenzo", team: "Napoli", role: "D", initial_price: 12 },
  { id: "q-4317", name: "N'Dicka", team: "Roma", role: "D", initial_price: 12 },
  { id: "q-4807", name: "Hermoso", team: "Roma", role: "D", initial_price: 11 },
  { id: "q-5982", name: "Spence", team: "Inter", role: "D", initial_price: 11 },
  { id: "q-5526", name: "Scalvini", team: "Atalanta", role: "D", initial_price: 10 },
  { id: "q-5750", name: "Ostigard", team: "Genoa", role: "D", initial_price: 10 },
  { id: "q-5641", name: "Chalobah T.", team: "Como", role: "D", initial_price: 10 },
  { id: "q-5885", name: "Dodò", team: "Fiorentina", role: "D", initial_price: 9 },
  { id: "q-5514", name: "Vasquez", team: "Genoa", role: "D", initial_price: 9 },
  { id: "q-6989", name: "Tiago Gabriel", team: "Lecce", role: "D", initial_price: 9 },
  { id: "q-7485", name: "Mangas", team: "Monza", role: "D", initial_price: 9 },
  { id: "q-5862", name: "Valeri", team: "Parma", role: "D", initial_price: 9 },
  { id: "q-5555", name: "Kamara H.", team: "Udinese", role: "D", initial_price: 9 },
  { id: "q-6727", name: "Couto", team: "Como", role: "D", initial_price: 9 },
  { id: "q-554", name: "Zappacosta", team: "Atalanta", role: "D", initial_price: 8 },
  { id: "q-6042", name: "Lucumì", team: "Juventus", role: "D", initial_price: 8 },
  { id: "q-4734", name: "Miranda J.", team: "Bologna", role: "D", initial_price: 8 },
  { id: "q-5701", name: "Obert", team: "Cagliari", role: "D", initial_price: 8 },
  { id: "q-7414", name: "Kaiki", team: "Como", role: "D", initial_price: 8 },
  { id: "q-5365", name: "Dragusin", team: "Fiorentina", role: "D", initial_price: 8 },
  { id: "q-6531", name: "Jimenez A.", team: "Fiorentina", role: "D", initial_price: 8 },
  { id: "q-5520", name: "Cambiaso", team: "Juventus", role: "D", initial_price: 8 },
  { id: "q-6320", name: "Doekhi", team: "Lazio", role: "D", initial_price: 8 },
  { id: "q-6496", name: "Bartesaghi", team: "Milan", role: "D", initial_price: 8 },
  { id: "q-1852", name: "Spinazzola", team: "Napoli", role: "D", initial_price: 8 },
  { id: "q-6664", name: "Delprato", team: "Parma", role: "D", initial_price: 8 },
  { id: "q-6495", name: "Comuzzo", team: "Torino", role: "D", initial_price: 8 },
  { id: "q-4994", name: "Vojvoda", team: "Udinese", role: "D", initial_price: 8 },
  { id: "q-5675", name: "Theate", team: "Bologna", role: "D", initial_price: 8 },
  { id: "q-7220", name: "Belghali", team: "Torino", role: "D", initial_price: 8 },
  { id: "q-4137", name: "Diego Carlos", team: "Parma", role: "D", initial_price: 8 },
  { id: "q-6046", name: "Hien", team: "Atalanta", role: "D", initial_price: 7 },
  { id: "q-4210", name: "Mina", team: "Cagliari", role: "D", initial_price: 7 },
  { id: "q-7274", name: "Zè Pedro", team: "Cagliari", role: "D", initial_price: 7 },
  { id: "q-6867", name: "Valle", team: "Como", role: "D", initial_price: 7 },
  { id: "q-7469", name: "Bracaglia", team: "Frosinone", role: "D", initial_price: 7 },
  { id: "q-6238", name: "Oyono A.", team: "Frosinone", role: "D", initial_price: 7 },
  { id: "q-4657", name: "Celik", team: "Juventus", role: "D", initial_price: 7 },
  { id: "q-5620", name: "Tavares N.", team: "Lazio", role: "D", initial_price: 7 },
  { id: "q-7529", name: "Koulierakis", team: "Roma", role: "D", initial_price: 7 },
  { id: "q-6672", name: "Idzes", team: "Sassuolo", role: "D", initial_price: 7 },
  { id: "q-5851", name: "Doig", team: "Sassuolo", role: "D", initial_price: 7 },
  { id: "q-6642", name: "Coco", team: "Torino", role: "D", initial_price: 7 },
  { id: "q-5010", name: "Ismajli", team: "Torino", role: "D", initial_price: 7 },
  { id: "q-7069", name: "Fortini", team: "Torino", role: "D", initial_price: 7 },
  { id: "q-7564", name: "Leysen F.", team: "Sassuolo", role: "D", initial_price: 7 },
  { id: "q-4705", name: "Balerdi", team: "Roma", role: "D", initial_price: 7 },
  { id: "q-2640", name: "Kolasinac", team: "Atalanta", role: "D", initial_price: 6 },
  { id: "q-7219", name: "Bernasconi", team: "Atalanta", role: "D", initial_price: 6 },
  { id: "q-7212", name: "Heggem", team: "Bologna", role: "D", initial_price: 6 },
  { id: "q-5678", name: "Holm", team: "Bologna", role: "D", initial_price: 6 },
  { id: "q-4433", name: "Zortea", team: "Bologna", role: "D", initial_price: 6 },
  { id: "q-6893", name: "Kempf", team: "Como", role: "D", initial_price: 6 },
  { id: "q-7410", name: "Viery", team: "Fiorentina", role: "D", initial_price: 6 },
  { id: "q-7467", name: "Calvani", team: "Frosinone", role: "D", initial_price: 6 },
  { id: "q-4952", name: "Monterisi", team: "Frosinone", role: "D", initial_price: 6 },
  { id: "q-6660", name: "Marcandalli", team: "Genoa", role: "D", initial_price: 6 },
  { id: "q-4177", name: "Pavard", team: "Inter", role: "D", initial_price: 6 },
  { id: "q-2188", name: "Marusic", team: "Lazio", role: "D", initial_price: 6 },
  { id: "q-6990", name: "Veiga D.", team: "Lecce", role: "D", initial_price: 6 },
  { id: "q-4502", name: "Gallo", team: "Lecce", role: "D", initial_price: 6 },
  { id: "q-4401", name: "Gabbia", team: "Milan", role: "D", initial_price: 6 },
  { id: "q-4751", name: "Tomori", team: "Milan", role: "D", initial_price: 6 },
  { id: "q-5838", name: "Birindelli", team: "Monza", role: "D", initial_price: 6 },
  { id: "q-2724", name: "Buongiorno", team: "Napoli", role: "D", initial_price: 6 },
  { id: "q-6485", name: "Kristensen T.", team: "Atalanta", role: "D", initial_price: 6 },
  { id: "q-6821", name: "Hainaut", team: "Venezia", role: "D", initial_price: 6 },
  { id: "q-7329", name: "Obrador", team: "Sassuolo", role: "D", initial_price: 6 },
  { id: "q-4664", name: "Badiashile", team: "Napoli", role: "D", initial_price: 6 },
  { id: "q-7580", name: "Sutalo J.", team: "Lazio", role: "D", initial_price: 6 },
  { id: "q-4147", name: "Caleta-Car", team: "Sassuolo", role: "D", initial_price: 6 },
  { id: "q-7621", name: "Sugawara", team: "Cagliari", role: "D", initial_price: 6 },
  { id: "q-6319", name: "Leite", team: "Lazio", role: "D", initial_price: 6 },
  { id: "q-4887", name: "Bellanova", team: "Atalanta", role: "D", initial_price: 5 },
  { id: "q-7532", name: "Kofler", team: "Cagliari", role: "D", initial_price: 5 },
  { id: "q-7268", name: "Rodriguez Ju.", team: "Cagliari", role: "D", initial_price: 5 },
  { id: "q-7294", name: "Valdepenas", team: "Fiorentina", role: "D", initial_price: 5 },
  { id: "q-5831", name: "Gatti", team: "Juventus", role: "D", initial_price: 5 },
  { id: "q-6766", name: "Kelly L.", team: "Juventus", role: "D", initial_price: 5 },
  { id: "q-4817", name: "Pedraza", team: "Lazio", role: "D", initial_price: 5 },
  { id: "q-7240", name: "Siebert", team: "Lecce", role: "D", initial_price: 5 },
  { id: "q-5739", name: "De Winter", team: "Milan", role: "D", initial_price: 5 },
  { id: "q-6202", name: "Beukema", team: "Napoli", role: "D", initial_price: 5 },
  { id: "q-6631", name: "Ghilardi", team: "Roma", role: "D", initial_price: 5 },
  { id: "q-7526", name: "Comert", team: "Torino", role: "D", initial_price: 5 },
  { id: "q-6021", name: "Abankwah", team: "Udinese", role: "D", initial_price: 5 },
  { id: "q-7253", name: "Bella-Kotchap", team: "Venezia", role: "D", initial_price: 5 },
  { id: "q-4845", name: "Correia T.", team: "Venezia", role: "D", initial_price: 5 },
  { id: "q-5695", name: "Haps", team: "Venezia", role: "D", initial_price: 5 },
  { id: "q-7563", name: "Favasuli", team: "Napoli", role: "D", initial_price: 5 },
  { id: "q-5751", name: "Patterson", team: "Torino", role: "D", initial_price: 5 },
  { id: "q-2169", name: "Rodriguez R.", team: "Torino", role: "D", initial_price: 5 },
  { id: "q-7068", name: "Vitik", team: "Bologna", role: "D", initial_price: 4 },
  { id: "q-5449", name: "Parisi", team: "Fiorentina", role: "D", initial_price: 4 },
  { id: "q-5757", name: "Cittadini", team: "Frosinone", role: "D", initial_price: 4 },
  { id: "q-7012", name: "Provstgaard", team: "Lazio", role: "D", initial_price: 4 },
  { id: "q-7131", name: "Floriani Mussolini", team: "Lazio", role: "D", initial_price: 4 },
  { id: "q-6632", name: "Gaspar K.", team: "Lecce", role: "D", initial_price: 4 },
  { id: "q-6659", name: "Lucchesi", team: "Monza", role: "D", initial_price: 4 },
  { id: "q-7238", name: "Kouadio", team: "Monza", role: "D", initial_price: 4 },
  { id: "q-4925", name: "Carboni A.", team: "Monza", role: "D", initial_price: 4 },
  { id: "q-5840", name: "Olivera", team: "Napoli", role: "D", initial_price: 4 },
  { id: "q-7235", name: "Troilo", team: "Parma", role: "D", initial_price: 4 },
  { id: "q-5307", name: "Valenti", team: "Parma", role: "D", initial_price: 4 },
  { id: "q-7255", name: "Britschgi", team: "Parma", role: "D", initial_price: 4 },
  { id: "q-6986", name: "Rensch", team: "Roma", role: "D", initial_price: 4 },
  { id: "q-5820", name: "Bertola", team: "Udinese", role: "D", initial_price: 4 },
  { id: "q-6890", name: "Moreno M.", team: "Venezia", role: "D", initial_price: 4 },
  { id: "q-6681", name: "Sagrado", team: "Venezia", role: "D", initial_price: 4 },
  { id: "q-4375", name: "Terzic", team: "Frosinone", role: "D", initial_price: 4 },
  { id: "q-7573", name: "Cinquegrano", team: "Sassuolo", role: "D", initial_price: 4 },
  { id: "q-256", name: "Juan Jesus", team: "Venezia", role: "D", initial_price: 4 },
  { id: "q-6047", name: "Ehizibue", team: "Genoa", role: "D", initial_price: 4 },
  { id: "q-5578", name: "Kossounou", team: "Atalanta", role: "D", initial_price: 3 },
  { id: "q-7326", name: "Helland", team: "Bologna", role: "D", initial_price: 3 },
  { id: "q-7014", name: "Smolcic I.", team: "Como", role: "D", initial_price: 3 },
  { id: "q-5603", name: "Pongracic", team: "Fiorentina", role: "D", initial_price: 3 },
  { id: "q-4378", name: "Ranieri L.", team: "Fiorentina", role: "D", initial_price: 3 },
  { id: "q-7537", name: "Mitaj", team: "Genoa", role: "D", initial_price: 3 },
  { id: "q-5273", name: "Estupinan", team: "Milan", role: "D", initial_price: 3 },
  { id: "q-4374", name: "Walukiewicz", team: "Sassuolo", role: "D", initial_price: 3 },
  { id: "q-4263", name: "Kabasele", team: "Udinese", role: "D", initial_price: 3 },
  { id: "q-5994", name: "Ebosse", team: "Udinese", role: "D", initial_price: 3 },
  { id: "q-5527", name: "Zanoli", team: "Udinese", role: "D", initial_price: 3 },
  { id: "q-7312", name: "Arizala", team: "Udinese", role: "D", initial_price: 3 },
  { id: "q-7154", name: "Odenthal", team: "Sassuolo", role: "D", initial_price: 3 },
  { id: "q-7599", name: "Lulli", team: "Roma", role: "D", initial_price: 3 },
  { id: "q-5742", name: "Drameh", team: "Genoa", role: "D", initial_price: 3 },
  { id: "q-5498", name: "Casale", team: "Bologna", role: "D", initial_price: 2 },
  { id: "q-7483", name: "Alhassane", team: "Bologna", role: "D", initial_price: 2 },
  { id: "q-7125", name: "Idrissi R.", team: "Cagliari", role: "D", initial_price: 2 },
  { id: "q-7175", name: "Joao Mario", team: "Fiorentina", role: "D", initial_price: 2 },
  { id: "q-7540", name: "Akpoguma", team: "Frosinone", role: "D", initial_price: 2 },
  { id: "q-6977", name: "Otoa", team: "Genoa", role: "D", initial_price: 2 },
  { id: "q-791", name: "Sabelli", team: "Genoa", role: "D", initial_price: 2 },
  { id: "q-7476", name: "Bakoune", team: "Monza", role: "D", initial_price: 2 },
  { id: "q-6638", name: "Marin R.", team: "Napoli", role: "D", initial_price: 2 },
  { id: "q-6985", name: "Candè", team: "Sassuolo", role: "D", initial_price: 2 },
  { id: "q-6925", name: "Palma", team: "Udinese", role: "D", initial_price: 2 },
  { id: "q-7538", name: "Halhal", team: "Venezia", role: "D", initial_price: 2 },
  { id: "q-6892", name: "Schingtienne", team: "Venezia", role: "D", initial_price: 2 },
  { id: "q-6673", name: "Sverko", team: "Venezia", role: "D", initial_price: 2 },
  { id: "q-7478", name: "Franjic", team: "Venezia", role: "D", initial_price: 2 },
  { id: "q-6537", name: "Goglichidze", team: "Monza", role: "D", initial_price: 2 },
  { id: "q-7605", name: "Tchato", team: "Frosinone", role: "D", initial_price: 2 },
  { id: "q-6601", name: "Kambwala", team: "Como", role: "D", initial_price: 2 },
  { id: "q-7615", name: "Drobnic", team: "Parma", role: "D", initial_price: 2 },
  { id: "q-487", name: "De Silvestri", team: "Bologna", role: "D", initial_price: 1 },
  { id: "q-418", name: "Goldaniga", team: "Como", role: "D", initial_price: 1 },
  { id: "q-6896", name: "Van Der Brempt", team: "Sassuolo", role: "D", initial_price: 1 },
  { id: "q-5424", name: "Amey", team: "Frosinone", role: "D", initial_price: 1 },
  { id: "q-7413", name: "Puczka", team: "Genoa", role: "D", initial_price: 1 },
  { id: "q-294", name: "Rugani", team: "Juventus", role: "D", initial_price: 1 },
  { id: "q-6039", name: "Cabal", team: "Juventus", role: "D", initial_price: 1 },
  { id: "q-327", name: "Patric", team: "Lazio", role: "D", initial_price: 1 },
  { id: "q-2263", name: "Lazzari", team: "Lazio", role: "D", initial_price: 1 },
  { id: "q-2728", name: "Pellegrini Lu.", team: "Lazio", role: "D", initial_price: 1 },
  { id: "q-6883", name: "Jean", team: "Lecce", role: "D", initial_price: 1 },
  { id: "q-7182", name: "Ndaba", team: "Lecce", role: "D", initial_price: 1 },
  { id: "q-7525", name: "Diawara S.", team: "Milan", role: "D", initial_price: 1 },
  { id: "q-5399", name: "Antov", team: "Monza", role: "D", initial_price: 1 },
  { id: "q-6809", name: "Marianucci", team: "Napoli", role: "D", initial_price: 1 },
  { id: "q-5481", name: "Mazzocchi", team: "Venezia", role: "D", initial_price: 1 },
  { id: "q-7202", name: "Ndiaye", team: "Parma", role: "D", initial_price: 1 },
  { id: "q-6149", name: "Carboni F.", team: "Parma", role: "D", initial_price: 1 },
  { id: "q-7260", name: "Ziolkowski", team: "Monza", role: "D", initial_price: 1 },
  { id: "q-7156", name: "Pieragnolo", team: "Sassuolo", role: "D", initial_price: 1 },
  { id: "q-252", name: "Biraghi", team: "Torino", role: "D", initial_price: 1 },
  { id: "q-7454", name: "Gomes", team: "Venezia", role: "D", initial_price: 1 },
  { id: "q-7548", name: "Aurelio", team: "Cagliari", role: "D", initial_price: 1 },
  { id: "q-7553", name: "Omar Fayed", team: "Frosinone", role: "D", initial_price: 1 },
  { id: "q-5812", name: "Terracciano F.", team: "Milan", role: "D", initial_price: 1 },
  { id: "q-7604", name: "Maye", team: "Monza", role: "D", initial_price: 1 },
  { id: "q-6826", name: "Dembelè A.", team: "Lecce", role: "D", initial_price: 1 },
  { id: "q-6875", name: "Paz N.", team: "Como", role: "C", initial_price: 30 },
  { id: "q-2194", name: "Calhanoglu", team: "Inter", role: "C", initial_price: 27 },
  { id: "q-4777", name: "McTominay", team: "Napoli", role: "C", initial_price: 26 },
  { id: "q-2167", name: "Orsolini", team: "Bologna", role: "C", initial_price: 24 },
  { id: "q-2423", name: "Pulisic", team: "Milan", role: "C", initial_price: 24 },
  { id: "q-2379", name: "Rabiot", team: "Milan", role: "C", initial_price: 23 },
  { id: "q-7126", name: "Baturina", team: "Como", role: "C", initial_price: 20 },
  { id: "q-7556", name: "Mora", team: "Roma", role: "C", initial_price: 20 },
  { id: "q-5559", name: "Da Cunha", team: "Como", role: "C", initial_price: 18 },
  { id: "q-1870", name: "Barella", team: "Inter", role: "C", initial_price: 18 },
  { id: "q-2517", name: "De Bruyne", team: "Napoli", role: "C", initial_price: 17 },
  { id: "q-2766", name: "Zaniolo", team: "Udinese", role: "C", initial_price: 17 },
  { id: "q-6908", name: "Atta", team: "Fiorentina", role: "C", initial_price: 16 },
  { id: "q-4973", name: "McKennie", team: "Juventus", role: "C", initial_price: 16 },
  { id: "q-632", name: "Zaccagni", team: "Lazio", role: "C", initial_price: 16 },
  { id: "q-7078", name: "Mastantuono", team: "Fiorentina", role: "C", initial_price: 14 },
  { id: "q-5119", name: "Samardzic", team: "Atalanta", role: "C", initial_price: 13 },
  { id: "q-5800", name: "Gudmundsson A.", team: "Lazio", role: "C", initial_price: 13 },
  { id: "q-152", name: "Zielinski", team: "Inter", role: "C", initial_price: 13 },
  { id: "q-6884", name: "Conceicao", team: "Juventus", role: "C", initial_price: 13 },
  { id: "q-7314", name: "Taylor K.", team: "Lazio", role: "C", initial_price: 13 },
  { id: "q-6684", name: "Ekkelenkamp", team: "Udinese", role: "C", initial_price: 13 },
  { id: "q-6372", name: "Moreira", team: "Milan", role: "C", initial_price: 13 },
  { id: "q-4179", name: "Gonzalez N.", team: "Juventus", role: "C", initial_price: 13 },
  { id: "q-5792", name: "Ederson D.S.", team: "Atalanta", role: "C", initial_price: 12 },
  { id: "q-2606", name: "Modric", team: "Milan", role: "C", initial_price: 12 },
  { id: "q-5687", name: "Vlasic", team: "Torino", role: "C", initial_price: 12 },
  { id: "q-5172", name: "Jones C.", team: "Inter", role: "C", initial_price: 12 },
  { id: "q-6151", name: "Perrone", team: "Como", role: "C", initial_price: 11 },
  { id: "q-7129", name: "Rodriguez Je.", team: "Como", role: "C", initial_price: 11 },
  { id: "q-5823", name: "Baldanzi", team: "Genoa", role: "C", initial_price: 11 },
  { id: "q-2848", name: "Frattesi", team: "Lazio", role: "C", initial_price: 11 },
  { id: "q-7436", name: "Alajbegovic", team: "Juventus", role: "C", initial_price: 11 },
  { id: "q-1850", name: "Kessiè", team: "Atalanta", role: "C", initial_price: 11 },
  { id: "q-7625", name: "Goncalves P.", team: "Fiorentina", role: "C", initial_price: 11 },
  { id: "q-184", name: "Bernardeschi", team: "Bologna", role: "C", initial_price: 10 },
  { id: "q-6844", name: "Rowe", team: "Atalanta", role: "C", initial_price: 10 },
  { id: "q-1933", name: "Mandragora", team: "Torino", role: "C", initial_price: 10 },
  { id: "q-6274", name: "Diouf", team: "Inter", role: "C", initial_price: 10 },
  { id: "q-5500", name: "Cancellieri", team: "Lazio", role: "C", initial_price: 10 },
  { id: "q-4892", name: "Saelemaekers", team: "Milan", role: "C", initial_price: 10 },
  { id: "q-4287", name: "Lobotka", team: "Napoli", role: "C", initial_price: 10 },
  { id: "q-4220", name: "Zambo Anguissa", team: "Napoli", role: "C", initial_price: 10 },
  { id: "q-536", name: "Politano", team: "Napoli", role: "C", initial_price: 10 },
  { id: "q-5589", name: "Konè M.", team: "Roma", role: "C", initial_price: 10 },
  { id: "q-5844", name: "Thorstvedt", team: "Sassuolo", role: "C", initial_price: 10 },
  { id: "q-7472", name: "Calò", team: "Frosinone", role: "C", initial_price: 9 },
  { id: "q-5562", name: "Thuram K.", team: "Juventus", role: "C", initial_price: 9 },
  { id: "q-6398", name: "Isaksen", team: "Lazio", role: "C", initial_price: 9 },
  { id: "q-5504", name: "Coulibaly L.", team: "Lecce", role: "C", initial_price: 9 },
  { id: "q-5878", name: "Colpani", team: "Monza", role: "C", initial_price: 9 },
  { id: "q-7223", name: "Vergara", team: "Napoli", role: "C", initial_price: 9 },
  { id: "q-779", name: "Cristante", team: "Roma", role: "C", initial_price: 9 },
  { id: "q-6677", name: "Adzic", team: "Sassuolo", role: "C", initial_price: 9 },
  { id: "q-5735", name: "Volpato", team: "Sassuolo", role: "C", initial_price: 9 },
  { id: "q-5888", name: "Casadei", team: "Torino", role: "C", initial_price: 9 },
  { id: "q-530", name: "Pellegrini Lo.", team: "Roma", role: "C", initial_price: 9 },
  { id: "q-2077", name: "Pasalic", team: "Atalanta", role: "C", initial_price: 8 },
  { id: "q-5858", name: "Ferguson", team: "Bologna", role: "C", initial_price: 8 },
  { id: "q-4436", name: "Cambiaghi", team: "Bologna", role: "C", initial_price: 8 },
  { id: "q-4870", name: "Adopo", team: "Cagliari", role: "C", initial_price: 8 },
  { id: "q-7311", name: "Romano", team: "Cagliari", role: "C", initial_price: 8 },
  { id: "q-4465", name: "Fagioli", team: "Fiorentina", role: "C", initial_price: 8 },
  { id: "q-6294", name: "Ndour", team: "Fiorentina", role: "C", initial_price: 8 },
  { id: "q-7070", name: "Sucic P.", team: "Inter", role: "C", initial_price: 8 },
  { id: "q-827", name: "Locatelli", team: "Juventus", role: "C", initial_price: 8 },
  { id: "q-5761", name: "Zhegrova", team: "Juventus", role: "C", initial_price: 8 },
  { id: "q-4856", name: "Chukwueze", team: "Milan", role: "C", initial_price: 8 },
  { id: "q-6190", name: "Pisilli", team: "Roma", role: "C", initial_price: 8 },
  { id: "q-6717", name: "Konè I.", team: "Sassuolo", role: "C", initial_price: 8 },
  { id: "q-6680", name: "Karlstrom", team: "Udinese", role: "C", initial_price: 8 },
  { id: "q-7551", name: "Schmid", team: "Frosinone", role: "C", initial_price: 8 },
  { id: "q-4364", name: "Gaetano", team: "Atalanta", role: "C", initial_price: 7 },
  { id: "q-5422", name: "Zalewski", team: "Atalanta", role: "C", initial_price: 7 },
  { id: "q-5298", name: "Pobega", team: "Bologna", role: "C", initial_price: 7 },
  { id: "q-2765", name: "Odgaard", team: "Bologna", role: "C", initial_price: 7 },
  { id: "q-4260", name: "Winks", team: "Cagliari", role: "C", initial_price: 7 },
  { id: "q-6010", name: "Fazzini", team: "Cagliari", role: "C", initial_price: 7 },
  { id: "q-5791", name: "Frendrup", team: "Genoa", role: "C", initial_price: 7 },
  { id: "q-5685", name: "Koopmeiners", team: "Juventus", role: "C", initial_price: 7 },
  { id: "q-6593", name: "Akinsanmiro", team: "Monza", role: "C", initial_price: 7 },
  { id: "q-6666", name: "Bernabè", team: "Parma", role: "C", initial_price: 7 },
  { id: "q-2528", name: "Matic", team: "Sassuolo", role: "C", initial_price: 7 },
  { id: "q-7060", name: "Cacciamani", team: "Torino", role: "C", initial_price: 7 },
  { id: "q-6783", name: "Unai Gomez", team: "Udinese", role: "C", initial_price: 7 },
  { id: "q-5507", name: "Busio", team: "Venezia", role: "C", initial_price: 7 },
  { id: "q-5946", name: "Sow", team: "Genoa", role: "C", initial_price: 7 },
  { id: "q-7618", name: "Hutchinson", team: "Milan", role: "C", initial_price: 7 },
  { id: "q-7619", name: "Monteiro J.", team: "Lecce", role: "C", initial_price: 7 },
  { id: "q-5680", name: "Sarr P.", team: "Juventus", role: "C", initial_price: 7 },
  { id: "q-6833", name: "Mbangula", team: "Bologna", role: "C", initial_price: 7 },
  { id: "q-7624", name: "Braganca", team: "Torino", role: "C", initial_price: 7 },
  { id: "q-795", name: "El Shaarawy", team: "Genoa", role: "C", initial_price: 7 },
  { id: "q-7412", name: "Milla", team: "Como", role: "C", initial_price: 6 },
  { id: "q-5036", name: "Caqueret", team: "Como", role: "C", initial_price: 6 },
  { id: "q-6678", name: "Liberali", team: "Como", role: "C", initial_price: 6 },
  { id: "q-7464", name: "Oulai", team: "Fiorentina", role: "C", initial_price: 6 },
  { id: "q-5998", name: "Zerbin", team: "Frosinone", role: "C", initial_price: 6 },
  { id: "q-6020", name: "Ellertsson", team: "Genoa", role: "C", initial_price: 6 },
  { id: "q-4459", name: "Rovella", team: "Lazio", role: "C", initial_price: 6 },
  { id: "q-6549", name: "Pierotti", team: "Lecce", role: "C", initial_price: 6 },
  { id: "q-2741", name: "Pessina", team: "Monza", role: "C", initial_price: 6 },
  { id: "q-6898", name: "Keita M.", team: "Parma", role: "C", initial_price: 6 },
  { id: "q-7036", name: "Bakola", team: "Sassuolo", role: "C", initial_price: 6 },
  { id: "q-7535", name: "Fitz-Jim", team: "Torino", role: "C", initial_price: 6 },
  { id: "q-6170", name: "Gineitis", team: "Torino", role: "C", initial_price: 6 },
  { id: "q-6218", name: "Oristanio", team: "Torino", role: "C", initial_price: 6 },
  { id: "q-7198", name: "Piotrowski", team: "Udinese", role: "C", initial_price: 6 },
  { id: "q-5674", name: "Basic", team: "Venezia", role: "C", initial_price: 6 },
  { id: "q-6994", name: "Perez K.", team: "Venezia", role: "C", initial_price: 6 },
  { id: "q-6618", name: "Cissè A.", team: "Milan", role: "C", initial_price: 6 },
  { id: "q-4479", name: "Elmas", team: "Atalanta", role: "C", initial_price: 6 },
  { id: "q-1871", name: "Deiola", team: "Cagliari", role: "C", initial_price: 5 },
  { id: "q-6640", name: "Felici", team: "Cagliari", role: "C", initial_price: 5 },
  { id: "q-6506", name: "Fini", team: "Frosinone", role: "C", initial_price: 5 },
  { id: "q-6917", name: "Masini", team: "Frosinone", role: "C", initial_price: 5 },
  { id: "q-4970", name: "Messias", team: "Genoa", role: "C", initial_price: 5 },
  { id: "q-7203", name: "Jashari", team: "Milan", role: "C", initial_price: 5 },
  { id: "q-5295", name: "Musah", team: "Milan", role: "C", initial_price: 5 },
  { id: "q-4349", name: "Nicolussi Caviglia", team: "Parma", role: "C", initial_price: 5 },
  { id: "q-6207", name: "Almqvist", team: "Parma", role: "C", initial_price: 5 },
  { id: "q-6827", name: "Njie", team: "Fiorentina", role: "C", initial_price: 5 },
  { id: "q-5319", name: "Sohm", team: "Venezia", role: "C", initial_price: 5 },
  { id: "q-7146", name: "Tourè I.", team: "Monza", role: "C", initial_price: 5 },
  { id: "q-22", name: "De Roon", team: "Roma", role: "C", initial_price: 4 },
  { id: "q-7528", name: "Amondarain", team: "Bologna", role: "C", initial_price: 4 },
  { id: "q-6054", name: "Moro N.", team: "Bologna", role: "C", initial_price: 4 },
  { id: "q-6895", name: "Dominguez B.", team: "Sassuolo", role: "C", initial_price: 4 },
  { id: "q-6815", name: "Fadera", team: "Cagliari", role: "C", initial_price: 4 },
  { id: "q-7127", name: "Addai", team: "Como", role: "C", initial_price: 4 },
  { id: "q-7473", name: "Cichella", team: "Frosinone", role: "C", initial_price: 4 },
  { id: "q-7341", name: "Amorim", team: "Genoa", role: "C", initial_price: 4 },
  { id: "q-7409", name: "Meichtry", team: "Genoa", role: "C", initial_price: 4 },
  { id: "q-2857", name: "Traorè Hj.", team: "Genoa", role: "C", initial_price: 4 },
  { id: "q-5301", name: "Luis Henrique", team: "Inter", role: "C", initial_price: 4 },
  { id: "q-2529", name: "Mkhitaryan", team: "Inter", role: "C", initial_price: 4 },
  { id: "q-6629", name: "Dele-Bashiru", team: "Lazio", role: "C", initial_price: 4 },
  { id: "q-5457", name: "Maleh", team: "Lecce", role: "C", initial_price: 4 },
  { id: "q-7322", name: "Ngom", team: "Lecce", role: "C", initial_price: 4 },
  { id: "q-6015", name: "Berisha M.", team: "Lecce", role: "C", initial_price: 4 },
  { id: "q-7318", name: "Gandelman", team: "Lecce", role: "C", initial_price: 4 },
  { id: "q-4199", name: "Loftus-Cheek", team: "Milan", role: "C", initial_price: 4 },
  { id: "q-6252", name: "Folorunsho", team: "Monza", role: "C", initial_price: 4 },
  { id: "q-6005", name: "Ilkhan", team: "Torino", role: "C", initial_price: 4 },
  { id: "q-7208", name: "Miller L.", team: "Udinese", role: "C", initial_price: 4 },
  { id: "q-7550", name: "Grillitsch", team: "Frosinone", role: "C", initial_price: 4 },
  { id: "q-7579", name: "Massolin", team: "Cagliari", role: "C", initial_price: 4 },
  { id: "q-6024", name: "Sulemana I.", team: "Sassuolo", role: "C", initial_price: 3 },
  { id: "q-4947", name: "Brescianini", team: "Fiorentina", role: "C", initial_price: 3 },
  { id: "q-6206", name: "Fabbian", team: "Parma", role: "C", initial_price: 3 },
  { id: "q-6903", name: "Hasa", team: "Frosinone", role: "C", initial_price: 3 },
  { id: "q-6191", name: "Belahyane", team: "Lazio", role: "C", initial_price: 3 },
  { id: "q-333", name: "Cataldi", team: "Lazio", role: "C", initial_price: 3 },
  { id: "q-7248", name: "Gorter", team: "Lecce", role: "C", initial_price: 3 },
  { id: "q-5453", name: "Ricci S.", team: "Como", role: "C", initial_price: 3 },
  { id: "q-5131", name: "Gilmour", team: "Napoli", role: "C", initial_price: 3 },
  { id: "q-7138", name: "Ordonez C.", team: "Parma", role: "C", initial_price: 3 },
  { id: "q-7536", name: "Diallo O.", team: "Parma", role: "C", initial_price: 3 },
  { id: "q-6246", name: "Lipani", team: "Sassuolo", role: "C", initial_price: 3 },
  { id: "q-5007", name: "Ilic", team: "Lecce", role: "C", initial_price: 3 },
  { id: "q-7183", name: "Aboukhlal", team: "Torino", role: "C", initial_price: 3 },
  { id: "q-801", name: "Gagliardini", team: "Cagliari", role: "C", initial_price: 3 },
  { id: "q-7232", name: "Fernandez T.", team: "Venezia", role: "C", initial_price: 3 },
  { id: "q-6225", name: "El Azzouzi O.", team: "Bologna", role: "C", initial_price: 2 },
  { id: "q-6241", name: "Gelli F.", team: "Frosinone", role: "C", initial_price: 2 },
  { id: "q-6503", name: "Stankovic A.", team: "Inter", role: "C", initial_price: 2 },
  { id: "q-7477", name: "Colombo L.", team: "Monza", role: "C", initial_price: 2 },
  { id: "q-7276", name: "Cremaschi", team: "Parma", role: "C", initial_price: 2 },
  { id: "q-6212", name: "Zarraga", team: "Udinese", role: "C", initial_price: 2 },
  { id: "q-7418", name: "Chakvetadze", team: "Udinese", role: "C", initial_price: 2 },
  { id: "q-5872", name: "Helgason", team: "Venezia", role: "C", initial_price: 2 },
  { id: "q-6592", name: "Forson O.", team: "Monza", role: "C", initial_price: 2 },
  { id: "q-7574", name: "Foe Ondoa", team: "Monza", role: "C", initial_price: 2 },
  { id: "q-7092", name: "Jovanovic", team: "Udinese", role: "C", initial_price: 2 },
  { id: "q-7628", name: "Sierro", team: "Parma", role: "C", initial_price: 2 },
  { id: "q-7165", name: "Liteta", team: "Cagliari", role: "C", initial_price: 1 },
  { id: "q-7357", name: "Lahdo", team: "Como", role: "C", initial_price: 1 },
  { id: "q-7456", name: "El Azzouzi A.", team: "Frosinone", role: "C", initial_price: 1 },
  { id: "q-5725", name: "Kone B.", team: "Frosinone", role: "C", initial_price: 1 },
  { id: "q-6980", name: "Venturino", team: "Genoa", role: "C", initial_price: 1 },
  { id: "q-7345", name: "Przyborek", team: "Lazio", role: "C", initial_price: 1 },
  { id: "q-6410", name: "Kaba", team: "Lecce", role: "C", initial_price: 1 },
  { id: "q-7319", name: "Fofana Sa.", team: "Lecce", role: "C", initial_price: 1 },
  { id: "q-5880", name: "Ciurria", team: "Monza", role: "C", initial_price: 1 },
  { id: "q-6219", name: "Boloca", team: "Sassuolo", role: "C", initial_price: 1 },
  { id: "q-7481", name: "Dagasso", team: "Venezia", role: "C", initial_price: 1 },
  { id: "q-526", name: "Duncan", team: "Venezia", role: "C", initial_price: 1 },
  { id: "q-7571", name: "Laerke", team: "Lecce", role: "C", initial_price: 1 },
  { id: "q-7572", name: "Comotto", team: "Milan", role: "C", initial_price: 1 },
  { id: "q-7575", name: "Mout", team: "Monza", role: "C", initial_price: 1 },
  { id: "q-5462", name: "Ciervo", team: "Cagliari", role: "C", initial_price: 1 },
  { id: "q-7629", name: "Libra", team: "Bologna", role: "C", initial_price: 1 },
  { id: "q-5850", name: "Lovric", team: "Udinese", role: "C", initial_price: 1 },
  { id: "q-5585", name: "Malen", team: "Roma", role: "A", initial_price: 37 },
  { id: "q-2764", name: "Martinez L.", team: "Inter", role: "A", initial_price: 34 },
  { id: "q-4871", name: "Thuram", team: "Inter", role: "A", initial_price: 30 },
  { id: "q-6052", name: "Hojlund", team: "Napoli", role: "A", initial_price: 28 },
  { id: "q-6397", name: "Ramos G.", team: "Milan", role: "A", initial_price: 26 },
  { id: "q-2097", name: "Kean", team: "Como", role: "A", initial_price: 24 },
  { id: "q-5951", name: "Kolo Muani", team: "Juventus", role: "A", initial_price: 24 },
  { id: "q-6752", name: "Woltemade", team: "Juventus", role: "A", initial_price: 22 },
  { id: "q-7017", name: "Douvikas", team: "Como", role: "A", initial_price: 21 },
  { id: "q-6434", name: "Yildiz", team: "Juventus", role: "A", initial_price: 21 },
  { id: "q-2137", name: "Scamacca", team: "Atalanta", role: "A", initial_price: 20 },
  { id: "q-5637", name: "Davis K.", team: "Udinese", role: "A", initial_price: 19 },
  { id: "q-7071", name: "Esposito F.P.", team: "Inter", role: "A", initial_price: 18 },
  { id: "q-531", name: "Berardi", team: "Sassuolo", role: "A", initial_price: 18 },
  { id: "q-6435", name: "Krstovic", team: "Atalanta", role: "A", initial_price: 17 },
  { id: "q-5995", name: "De Ketelaere", team: "Atalanta", role: "A", initial_price: 16 },
  { id: "q-6675", name: "Dovbyk", team: "Bologna", role: "A", initial_price: 16 },
  { id: "q-7023", name: "Pellegrino M.", team: "Fiorentina", role: "A", initial_price: 16 },
  { id: "q-309", name: "Dybala", team: "Roma", role: "A", initial_price: 16 },
  { id: "q-6060", name: "Laurientè", team: "Sassuolo", role: "A", initial_price: 16 },
  { id: "q-5734", name: "Soulè", team: "Roma", role: "A", initial_price: 15 },
  { id: "q-6967", name: "Diao", team: "Como", role: "A", initial_price: 14 },
  { id: "q-7351", name: "Santos A.", team: "Napoli", role: "A", initial_price: 14 },
  { id: "q-6572", name: "Castro S.", team: "Roma", role: "A", initial_price: 14 },
  { id: "q-2061", name: "Simeone", team: "Torino", role: "A", initial_price: 14 },
  { id: "q-5694", name: "Beto", team: "Fiorentina", role: "A", initial_price: 14 },
  { id: "q-4371", name: "Raspadori", team: "Atalanta", role: "A", initial_price: 13 },
  { id: "q-4463", name: "Esposito Se.", team: "Sassuolo", role: "A", initial_price: 13 },
  { id: "q-7484", name: "Adams A.", team: "Venezia", role: "A", initial_price: 12 },
  { id: "q-5436", name: "Raimondo", team: "Frosinone", role: "A", initial_price: 11 },
  { id: "q-7347", name: "Bowie", team: "Sassuolo", role: "A", initial_price: 11 },
  { id: "q-2038", name: "Pinamonti", team: "Lazio", role: "A", initial_price: 11 },
  { id: "q-6646", name: "Adams C.", team: "Torino", role: "A", initial_price: 11 },
  { id: "q-7547", name: "Kevin Carlos", team: "Cagliari", role: "A", initial_price: 11 },
  { id: "q-7554", name: "Romero D.", team: "Parma", role: "A", initial_price: 11 },
  { id: "q-4923", name: "Colombo", team: "Genoa", role: "A", initial_price: 10 },
  { id: "q-6904", name: "Yeboah J.", team: "Venezia", role: "A", initial_price: 10 },
  { id: "q-6229", name: "Tourè E.", team: "Parma", role: "A", initial_price: 10 },
  { id: "q-4896", name: "Maldini", team: "Cagliari", role: "A", initial_price: 9 },
  { id: "q-4359", name: "Piccoli", team: "Bologna", role: "A", initial_price: 9 },
  { id: "q-6530", name: "Ghedjemis", team: "Frosinone", role: "A", initial_price: 9 },
  { id: "q-6204", name: "Kvernadze", team: "Frosinone", role: "A", initial_price: 9 },
  { id: "q-2155", name: "Cutrone", team: "Monza", role: "A", initial_price: 9 },
  { id: "q-7600", name: "Osmajic", team: "Genoa", role: "A", initial_price: 9 },
  { id: "q-7612", name: "Bobcek", team: "Frosinone", role: "A", initial_price: 9 },
  { id: "q-6164", name: "Vitinha O.", team: "Genoa", role: "A", initial_price: 8 },
  { id: "q-6669", name: "Bonny", team: "Inter", role: "A", initial_price: 8 },
  { id: "q-6556", name: "Noslin", team: "Lazio", role: "A", initial_price: 8 },
  { id: "q-5029", name: "Geubbels", team: "Lecce", role: "A", initial_price: 8 },
  { id: "q-7374", name: "Mendy P.", team: "Cagliari", role: "A", initial_price: 7 },
  { id: "q-7252", name: "Stulic", team: "Lecce", role: "A", initial_price: 7 },
  { id: "q-7523", name: "Varela G.", team: "Monza", role: "A", initial_price: 7 },
  { id: "q-7449", name: "Rrahmani Al.", team: "Venezia", role: "A", initial_price: 7 },
  { id: "q-7620", name: "Zeballos", team: "Monza", role: "A", initial_price: 7 },
  { id: "q-7623", name: "Gnonto", team: "Fiorentina", role: "A", initial_price: 7 },
  { id: "q-2832", name: "Boga", team: "Juventus", role: "A", initial_price: 6 },
  { id: "q-608", name: "Zapata D.", team: "Torino", role: "A", initial_price: 6 },
  { id: "q-7272", name: "Gueye", team: "Udinese", role: "A", initial_price: 6 },
  { id: "q-7546", name: "Robinson J.", team: "Monza", role: "A", initial_price: 6 },
  { id: "q-5918", name: "Sulemana K.", team: "Atalanta", role: "A", initial_price: 5 },
  { id: "q-5882", name: "Mota", team: "Monza", role: "A", initial_price: 5 },
  { id: "q-6831", name: "Neres", team: "Napoli", role: "A", initial_price: 5 },
  { id: "q-7561", name: "Lontani", team: "Parma", role: "A", initial_price: 5 },
  { id: "q-7001", name: "N'Dri", team: "Lecce", role: "A", initial_price: 4 },
  { id: "q-6519", name: "Camarda", team: "Milan", role: "A", initial_price: 4 },
  { id: "q-7120", name: "Lang", team: "Napoli", role: "A", initial_price: 4 },
  { id: "q-7213", name: "Frigan", team: "Parma", role: "A", initial_price: 4 },
  { id: "q-4387", name: "Adorante", team: "Venezia", role: "A", initial_price: 4 },
  { id: "q-2012", name: "Milik", team: "Juventus", role: "A", initial_price: 4 },
  { id: "q-7602", name: "Fatah", team: "Lecce", role: "A", initial_price: 4 },
  { id: "q-7610", name: "Birligea", team: "Frosinone", role: "A", initial_price: 4 },
  { id: "q-6145", name: "Ngonge", team: "Monza", role: "A", initial_price: 4 },
  { id: "q-5336", name: "Nzola", team: "Cagliari", role: "A", initial_price: 4 },
  { id: "q-7453", name: "Havel", team: "Genoa", role: "A", initial_price: 3 },
  { id: "q-7162", name: "Giovane", team: "Napoli", role: "A", initial_price: 3 },
  { id: "q-6215", name: "Lucca", team: "Napoli", role: "A", initial_price: 3 },
  { id: "q-7342", name: "Elphege", team: "Parma", role: "A", initial_price: 3 },
  { id: "q-7349", name: "Kulenovic", team: "Torino", role: "A", initial_price: 3 },
  { id: "q-6822", name: "Ekhator", team: "Juventus", role: "A", initial_price: 2 },
  { id: "q-7482", name: "Lauberbach", team: "Venezia", role: "A", initial_price: 2 },
  { id: "q-7627", name: "Enem", team: "Bologna", role: "A", initial_price: 2 },
  { id: "q-7317", name: "Trepy", team: "Cagliari", role: "A", initial_price: 1 },
  { id: "q-7161", name: "Bayo V.", team: "Udinese", role: "A", initial_price: 1 },
  { id: "q-7408", name: "Lisman", team: "Venezia", role: "A", initial_price: 1 },
  { id: "q-7568", name: "De Martis", team: "Parma", role: "A", initial_price: 1 },
  { id: "q-7622", name: "Robinho Junior", team: "Genoa", role: "A", initial_price: 1 },
];

export const INITIAL_TEAMS = [
  {
    "id": "team-1",
    "league_id": "00000000-0000-0000-0000-000000000001",
    "name": "Birrareal",
    "manager_name": "Fabio (Admin)",
    "manager_email": "fabio.perfetti81@gmail.com",
    "is_admin": true,
    "initial_budget": 500,
    "order_index": 1
  },
  {
    "id": "team-2",
    "league_id": "00000000-0000-0000-0000-000000000001",
    "name": "Atletico Bulgao",
    "manager_name": "Bulga",
    "initial_budget": 500,
    "order_index": 2
  },
  {
    "id": "team-3",
    "league_id": "00000000-0000-0000-0000-000000000001",
    "name": "Babalu",
    "manager_name": "Cocco",
    "initial_budget": 500,
    "order_index": 3
  },
  {
    "id": "team-4",
    "league_id": "00000000-0000-0000-0000-000000000001",
    "name": "A.C. Circolo Vizioso",
    "manager_name": "Marco",
    "initial_budget": 500,
    "order_index": 4
  },
  {
    "id": "team-5",
    "league_id": "00000000-0000-0000-0000-000000000001",
    "name": "Pol. Porca Puttena",
    "manager_name": "Loppo",
    "initial_budget": 500,
    "order_index": 5
  },
  {
    "id": "team-6",
    "league_id": "00000000-0000-0000-0000-000000000001",
    "name": "Op Op Op Via",
    "manager_name": "Teo",
    "initial_budget": 500,
    "order_index": 6
  },
  {
    "id": "team-7",
    "league_id": "00000000-0000-0000-0000-000000000001",
    "name": "Atletico Maria",
    "manager_name": "Beppe",
    "initial_budget": 500,
    "order_index": 7
  },
  {
    "id": "team-8",
    "league_id": "00000000-0000-0000-0000-000000000001",
    "name": "Quartieri Spagnoli",
    "manager_name": "Tonio",
    "initial_budget": 500,
    "order_index": 8
  },
  {
    "id": "team-9",
    "league_id": "00000000-0000-0000-0000-000000000001",
    "name": "Real Perfect Team",
    "manager_name": "Ale",
    "initial_budget": 500,
    "order_index": 9
  },
  {
    "id": "team-10",
    "league_id": "00000000-0000-0000-0000-000000000001",
    "name": "Piangina Number One",
    "manager_name": "Viro",
    "initial_budget": 500,
    "order_index": 10
  }
];
